#!/usr/bin/env -S expect -f

set timeout 3
spawn ../../bin/composer_install.sh "" "" "../fixtures/custom-composer" "" "" "composer-gh-actions.lock" "" "composer-gh-actions"
match_max 100000

expect "::debug::Using the following Composer command: '*/php */composer install --no-interaction --no-progress --ansi --working-dir ../fixtures/custom-composer'"
expect "Installing dependencies"
expect "Generating autoload files"
expect eof

# Clean up
file delete -force ../fixtures/custom-composer/vendor
